# Generated by Django 5.0.2 on 2024-03-16 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('bug', 'Bug'), ('feature_request', 'Feature Request'), ('question', 'Question'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('closed_datetime', models.DateTimeField(blank=True, null=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('ticket_status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('resolved', 'Resolved'), ('in_progress', 'In Progress'), ('pending', 'Pending')], default='open', max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
